/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SchoolElection } from './SchoolElection.js';
export * as factories from './factories/index.js';
export { SchoolElection__factory } from './factories/SchoolElection__factory.js';