/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface SchoolElectionInterface extends Interface {
    getFunction(nameOrSignature: "addCandidate" | "admin" | "candidatesCount" | "electionActive" | "electionClosed" | "endElection" | "getCandidateVotes" | "personeroCount" | "registerStudent" | "startElection" | "vote"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ElectionEnded" | "ElectionStarted" | "VoteCast"): EventFragment;

    encodeFunctionData(functionFragment: 'addCandidate', values: [string, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
encodeFunctionData(functionFragment: 'candidatesCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'electionActive', values?: undefined): string;
encodeFunctionData(functionFragment: 'electionClosed', values?: undefined): string;
encodeFunctionData(functionFragment: 'endElection', values?: undefined): string;
encodeFunctionData(functionFragment: 'getCandidateVotes', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'personeroCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerStudent', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'startElection', values?: undefined): string;
encodeFunctionData(functionFragment: 'vote', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'addCandidate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'candidatesCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'electionActive', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'electionClosed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'endElection', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCandidateVotes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'personeroCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerStudent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'startElection', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vote', data: BytesLike): Result;
  }

  
    export namespace ElectionEndedEvent {
      export type InputTuple = [timestamp: BigNumberish];
      export type OutputTuple = [timestamp: bigint];
      export interface OutputObject {timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ElectionStartedEvent {
      export type InputTuple = [timestamp: BigNumberish];
      export type OutputTuple = [timestamp: bigint];
      export interface OutputObject {timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VoteCastEvent {
      export type InputTuple = [voter: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [voter: string, timestamp: bigint];
      export interface OutputObject {voter: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface SchoolElection extends BaseContract {
    
    connect(runner?: ContractRunner | null): SchoolElection;
    waitForDeployment(): Promise<this>;

    interface: SchoolElectionInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addCandidate: TypedContractMethod<
      [_name: string, _cargo: BigNumberish, _studentAddress: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    admin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    candidatesCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    electionActive: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    electionClosed: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    endElection: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    getCandidateVotes: TypedContractMethod<
      [_candidateId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    personeroCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    registerStudent: TypedContractMethod<
      [_student: AddressLike, _grade: BigNumberish, _antiquity: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    startElection: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    vote: TypedContractMethod<
      [_candidateId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addCandidate'): TypedContractMethod<
      [_name: string, _cargo: BigNumberish, _studentAddress: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'admin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'candidatesCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'electionActive'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'electionClosed'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'endElection'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getCandidateVotes'): TypedContractMethod<
      [_candidateId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'personeroCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'registerStudent'): TypedContractMethod<
      [_student: AddressLike, _grade: BigNumberish, _antiquity: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'startElection'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'vote'): TypedContractMethod<
      [_candidateId: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ElectionEnded'): TypedContractEvent<ElectionEndedEvent.InputTuple, ElectionEndedEvent.OutputTuple, ElectionEndedEvent.OutputObject>;
getEvent(key: 'ElectionStarted'): TypedContractEvent<ElectionStartedEvent.InputTuple, ElectionStartedEvent.OutputTuple, ElectionStartedEvent.OutputObject>;
getEvent(key: 'VoteCast'): TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;

    filters: {
      
      'ElectionEnded(uint256)': TypedContractEvent<ElectionEndedEvent.InputTuple, ElectionEndedEvent.OutputTuple, ElectionEndedEvent.OutputObject>;
      ElectionEnded: TypedContractEvent<ElectionEndedEvent.InputTuple, ElectionEndedEvent.OutputTuple, ElectionEndedEvent.OutputObject>;
    

      'ElectionStarted(uint256)': TypedContractEvent<ElectionStartedEvent.InputTuple, ElectionStartedEvent.OutputTuple, ElectionStartedEvent.OutputObject>;
      ElectionStarted: TypedContractEvent<ElectionStartedEvent.InputTuple, ElectionStartedEvent.OutputTuple, ElectionStartedEvent.OutputObject>;
    

      'VoteCast(address,uint256)': TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
      VoteCast: TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
    
    };
  }